### ISSUE TITLE
Launch Pathways MVP in Tennessee

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#1407]
**What needs to be done? Why does it need to be done?**
Tracking epic for Pathways in TN.

On the frontend, this includes supporting the following:
- [ ] Prison page
- [ ] Individuals list
- [ ] Additional filters module
- [ ] Prison population over time chart
- [ ] Prison population by facility breakdown chart

**Additional context**
Add any other context about the task here.
