### ISSUE TITLE
Add diffing for all metrics

### ISSUE THREAD

**Issue by danawillow** [Recidiviz/pulse-dashboard#1970]
All charts:
- [x] liberty_to_prison_count_by_month (#1920)
- [x] liberty_to_prison_population_snapshot_by_dimension (#1951)
- [ ] prison_population_time_series
- [ ] prison_population_projection_time_series 
- [ ] prison_population_snapshot_by_dimension
- [ ] prison_population_snapshot_person_level
- [x] prison_to_supervision_count_by_month (#2004)
- [x] prison_to_supervision_population_snapshot_by_dimension (#2004)
- [x] prison_to_supervision_population_snapshot_person_level (#1967)
- [ ] supervision_population_time_series
- [ ] supervision_population_projection_time_series
- [ ] supervision_population_snapshot_by_dimension
- [x] supervision_to_prison_count_by_month (#2004)
- [x] supervision_to_prison_population_snapshot_by_dimension (#2004)
- [x] supervision_to_prison_population_snapshot_by_officer (#2004)
- [x] supervision_to_liberty_count_by_month (#2004)
- [x] supervision_to_liberty_population_snapshot_by_dimension (#2004)
