### ISSUE TITLE
Support ND early termination workflows

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#2070]
**What needs to be done? Why does it need to be done?**
Slide brief here: https://docs.google.com/presentation/d/18N0CyGPOhE1SuXJ7-4E0K_kAjM91RVmkZR99pk9768U/edit#slide=id.g13dc2bed4f1_0_270

**New UI support needed**
- [ ] ND-specific copy, configured from spreadsheet
- [ ] Update Vitals icon to be different from Workflows
- [ ] Denied reasons modal: 3 types of reasons (one reason per criteria category, custom reason specified for that opp, open text "other")
- [ ] Multi-page PDF form automation, knowing that future tasks may be multi-step, or there may be multiple forms associated with a task

Assigning first to @soniachokshi for mocks. Then will re-assign to @Catacola and @danawillow to break down tickets once designs are ready.

**Additional context**
Add any other context about the task here.

**Comment by sychang** [comment]
Closing this duplicate epic, more up-to-date and complete: https://app.zenhub.com/workspaces/polaris-614c9f27fa19b10015ddd495/issues/recidiviz/pulse-dashboard/2076

**Comment by sychang** [comment]
Closing this duplicate epic, more up-to-date and complete: https://app.zenhub.com/workspaces/polaris-614c9f27fa19b10015ddd495/issues/recidiviz/pulse-dashboard/2076
