### ISSUE TITLE
[Launch checklist] CO Pathways v1 Launch

### ISSUE THREAD

**Issue by kirtanac** [Recidiviz/pulse-dashboard#2131]
Relevant links

PRD: [CO-specific Pathways v1 doc](https://docs.google.com/document/d/16kxa5nj6ofcmK4pgK2Pl2OvAd2Lt0NxfCABWeDUbe7E/edit). [CO bug bash and  v1 launch review](https://docs.google.com/document/d/1E0W6g21rqqo1oAT4gUjS9WpoFpNLyjy2WtfU-m5exgw/edit#heading=h.wys0ga4vxb6a)
Engineering Design Docs: N/A
Mocks or staging: https://dashboard-staging.recidiviz.org/ > Colorado
End user documentation: N/A
Comms doc: (N/A unless Medium or Large change)
Privacy design doc: Same principally as ND launch
Change management schedule: N/A
What size change is being launched?
Medium

Which states or clients is this change going to? Which non-state organizations will have access?
Colorado DOC leadership. 

Write a short description of the change:

Does this change collect or show any new PII (of state staff, individuals under supervision or in facilities, etc.)?

Yes, new lists of individuals shown on more pages. Previously just people in facilities were showing, but conceptually the tool is the same.

Will this change require change management (managing end-users from an existing workflow to a new workflow)?
No

Launch approval checklist. Check box and add date when sign-off is obtained

FYI Exec: @clementinej, @jessex [08/03/22]
FYI Product: @cawarren [MM/DD/YY]
- [x] Eng: @Catacola, FYI @jovergaag @danawillow [08/02/22]
- [x] Data: @lydiamasri2  [08/02/22]
FYI Security: @phenggeler [MM/DD/YY]
FYI Compliance: @phenggeler [MM/DD/YY]
- [x] Comms: @ushawsmi  [MM/DD/YY]
- [x] Docs: @ushawsmi  [MM/DD/YY]
FYI Design: @agr0n [MM/DD/YY]
FYI Legal: @cawarren [MM/DD/YY]
FYI Privacy: @cawarren [MM/DD/YY]
FYI Accessibility: @cawarren [MM/DD/YY]
FYI Localization: Usually N/A
–––––––––––––––––– GLOSSARY ––––––––––––––––––

Launch size: A launch’s size is a rough estimate of its ‘splash’ - with users, with the press, etc. For example:

Large launch examples: New product offering or tool, major redesign or re-launch of existing product or tool.
Medium launch examples: Launching an existing product or tool to a new state, adding a significant new feature in existing product or tool, updating the design in a noticeable way for an existing feature or set of features,
Minor launch examples: Small feature additions or changes to existing products or tools, improvements to methodology or ease of use. Generally not noticeable to the majority of end-users.

**Comment by phenggeler** [comment]
@kirtanac and @lydiamasri2 - is this simply a launch of Pathways in Colorado? I've signed off on Pathways launches going forward for other states since I've worked through the security and compliance questions in previous rounds with the Polaris team.

**Comment by kirtanac** [comment]
Hi @phenggeler , yes it is! Awesome great to hear :)
