### ISSUE TITLE
[US_ID] Community vitals web page

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#771]
**What needs to be done? Why does it need to be done?**
This epic tracks tasks related to launching the vitals page of the web tool in ID.

PRD here: https://docs.google.com/document/d/1moftAcmQ2JWddxwI99btG0DDSC8fBIChwfysb6Hvam4/edit#heading=h.xzg9x9axpa3q

Burndown here: https://docs.google.com/document/d/1T6CiyecfnX1ZUhF4bDcr-MGNtVzEUMhIHUVthxpqwDY/edit?usp=sharing

Tasks
- [x] Get and validate data needed for ID vitals
- [x] Finalize and incorporate methodology and copy for vitals 
- [x] Create a button that allows supervisors to access Case Triage from officer view, coordinate with read-only mode from Cosmos ([ticket here](https://app.zenhub.com/workspaces/cosmos-aka-line-staff-tools-5fd7950b2ceba10011b87ebd/issues/recidiviz/recidiviz-data/8184)) 

**Additional context**
Add any other context about the task here.

**Comment by sychang** [comment]
Methodology here, also linking in the methodology ticket: https://docs.google.com/document/d/1moftAcmQ2JWddxwI99btG0DDSC8fBIChwfysb6Hvam4/edit#heading=h.zaj0dhwrazbu
